// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_custom_status

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func CustomStatusResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"custom_status": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"active": schema.BoolAttribute{
						Optional:            true,
						Computed:            true,
						Description:         "True if the custom status is set as active; inactive if false",
						MarkdownDescription: "True if the custom status is set as active; inactive if false",
					},
					"agent_label": schema.StringAttribute{
						Optional:            true,
						Computed:            true,
						Description:         "The dynamic content placeholder, if present, or the \"agent_label\" value, if not. See [Dynamic Content Items](/api-reference/ticketing/ticket-management/dynamic_content/)",
						MarkdownDescription: "The dynamic content placeholder, if present, or the \"agent_label\" value, if not. See [Dynamic Content Items](/api-reference/ticketing/ticket-management/dynamic_content/)",
					},
					"created_at": schema.StringAttribute{
						Computed:            true,
						Description:         "The date and time the custom ticket status was created",
						MarkdownDescription: "The date and time the custom ticket status was created",
					},
					"default": schema.BoolAttribute{
						Computed:            true,
						Description:         "If true, the custom status is set to default. If false, the custom status is set to non-default",
						MarkdownDescription: "If true, the custom status is set to default. If false, the custom status is set to non-default",
					},
					"description": schema.StringAttribute{
						Optional:            true,
						Computed:            true,
						Description:         "The dynamic content placeholder, if present, or the \"description\" value, if not. See [Dynamic Content Items](/api-reference/ticketing/ticket-management/dynamic_content/)",
						MarkdownDescription: "The dynamic content placeholder, if present, or the \"description\" value, if not. See [Dynamic Content Items](/api-reference/ticketing/ticket-management/dynamic_content/)",
					},
					"end_user_description": schema.StringAttribute{
						Optional:            true,
						Computed:            true,
						Description:         "The dynamic content placeholder, if present, or the \"end_user_description\" value, if not. See [Dynamic Content Items](/api-reference/ticketing/ticket-management/dynamic_content/)",
						MarkdownDescription: "The dynamic content placeholder, if present, or the \"end_user_description\" value, if not. See [Dynamic Content Items](/api-reference/ticketing/ticket-management/dynamic_content/)",
					},
					"end_user_label": schema.StringAttribute{
						Optional:            true,
						Computed:            true,
						Description:         "The dynamic content placeholder, if present, or the \"end_user_label\" value, if not. See [Dynamic Content Items](/api-reference/ticketing/ticket-management/dynamic_content/)",
						MarkdownDescription: "The dynamic content placeholder, if present, or the \"end_user_label\" value, if not. See [Dynamic Content Items](/api-reference/ticketing/ticket-management/dynamic_content/)",
					},
					"id": schema.Int64Attribute{
						Computed:            true,
						Description:         "Automatically assigned when the custom ticket status is created",
						MarkdownDescription: "Automatically assigned when the custom ticket status is created",
					},
					"raw_agent_label": schema.StringAttribute{
						Computed:            true,
						Description:         "The dynamic content placeholder. If the dynamic content placeholder is not available, this is the \"agent_label\" value. See [Dynamic Content Items](/api-reference/ticketing/ticket-management/dynamic_content/)",
						MarkdownDescription: "The dynamic content placeholder. If the dynamic content placeholder is not available, this is the \"agent_label\" value. See [Dynamic Content Items](/api-reference/ticketing/ticket-management/dynamic_content/)",
					},
					"raw_description": schema.StringAttribute{
						Computed:            true,
						Description:         "The dynamic content placeholder. If the dynamic content placeholder is not available, this is the \"description\" value. [Dynamic Content Items](/api-reference/ticketing/ticket-management/dynamic_content/)",
						MarkdownDescription: "The dynamic content placeholder. If the dynamic content placeholder is not available, this is the \"description\" value. [Dynamic Content Items](/api-reference/ticketing/ticket-management/dynamic_content/)",
					},
					"raw_end_user_description": schema.StringAttribute{
						Computed:            true,
						Description:         "The dynamic content placeholder. If the dynamic content placeholder is not available, this is the \"end_user_description\" value. See [Dynamic Content Items](/api-reference/ticketing/ticket-management/dynamic_content/)",
						MarkdownDescription: "The dynamic content placeholder. If the dynamic content placeholder is not available, this is the \"end_user_description\" value. See [Dynamic Content Items](/api-reference/ticketing/ticket-management/dynamic_content/)",
					},
					"raw_end_user_label": schema.StringAttribute{
						Computed:            true,
						Description:         "The dynamic content placeholder. If the dynamic content placeholder is not available, this is the \"end_user_label\" value. See [Dynamic Content Items](/api-reference/ticketing/ticket-management/dynamic_content/)",
						MarkdownDescription: "The dynamic content placeholder. If the dynamic content placeholder is not available, this is the \"end_user_label\" value. See [Dynamic Content Items](/api-reference/ticketing/ticket-management/dynamic_content/)",
					},
					"status_category": schema.StringAttribute{
						Optional:            true,
						Computed:            true,
						Description:         "The status category the custom ticket status belongs to",
						MarkdownDescription: "The status category the custom ticket status belongs to",
						Validators: []validator.String{
							stringvalidator.OneOf(
								"new",
								"open",
								"pending",
								"hold",
								"solved",
							),
						},
					},
					"updated_at": schema.StringAttribute{
						Computed:            true,
						Description:         "The date and time the custom ticket status was last updated",
						MarkdownDescription: "The date and time the custom ticket status was last updated",
					},
				},
				CustomType: CustomStatusType{
					ObjectType: types.ObjectType{
						AttrTypes: CustomStatusValue{}.AttributeTypes(ctx),
					},
				},
				Optional: true,
				Computed: true,
			},
			"custom_status_id": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "The id of the custom status",
				MarkdownDescription: "The id of the custom status",
			},
		},
	}
}

type CustomStatusModel struct {
	CustomStatus   CustomStatusValue `tfsdk:"custom_status"`
	CustomStatusId types.Int64       `tfsdk:"custom_status_id"`
}

var _ basetypes.ObjectTypable = CustomStatusType{}

type CustomStatusType struct {
	basetypes.ObjectType
}

func (t CustomStatusType) Equal(o attr.Type) bool {
	other, ok := o.(CustomStatusType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t CustomStatusType) String() string {
	return "CustomStatusType"
}

func (t CustomStatusType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	activeAttribute, ok := attributes["active"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`active is missing from object`)

		return nil, diags
	}

	activeVal, ok := activeAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`active expected to be basetypes.BoolValue, was: %T`, activeAttribute))
	}

	agentLabelAttribute, ok := attributes["agent_label"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`agent_label is missing from object`)

		return nil, diags
	}

	agentLabelVal, ok := agentLabelAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`agent_label expected to be basetypes.StringValue, was: %T`, agentLabelAttribute))
	}

	createdAtAttribute, ok := attributes["created_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`created_at is missing from object`)

		return nil, diags
	}

	createdAtVal, ok := createdAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`created_at expected to be basetypes.StringValue, was: %T`, createdAtAttribute))
	}

	defaultAttribute, ok := attributes["default"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`default is missing from object`)

		return nil, diags
	}

	defaultVal, ok := defaultAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`default expected to be basetypes.BoolValue, was: %T`, defaultAttribute))
	}

	descriptionAttribute, ok := attributes["description"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`description is missing from object`)

		return nil, diags
	}

	descriptionVal, ok := descriptionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`description expected to be basetypes.StringValue, was: %T`, descriptionAttribute))
	}

	endUserDescriptionAttribute, ok := attributes["end_user_description"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`end_user_description is missing from object`)

		return nil, diags
	}

	endUserDescriptionVal, ok := endUserDescriptionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`end_user_description expected to be basetypes.StringValue, was: %T`, endUserDescriptionAttribute))
	}

	endUserLabelAttribute, ok := attributes["end_user_label"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`end_user_label is missing from object`)

		return nil, diags
	}

	endUserLabelVal, ok := endUserLabelAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`end_user_label expected to be basetypes.StringValue, was: %T`, endUserLabelAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.Int64Value, was: %T`, idAttribute))
	}

	rawAgentLabelAttribute, ok := attributes["raw_agent_label"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`raw_agent_label is missing from object`)

		return nil, diags
	}

	rawAgentLabelVal, ok := rawAgentLabelAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`raw_agent_label expected to be basetypes.StringValue, was: %T`, rawAgentLabelAttribute))
	}

	rawDescriptionAttribute, ok := attributes["raw_description"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`raw_description is missing from object`)

		return nil, diags
	}

	rawDescriptionVal, ok := rawDescriptionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`raw_description expected to be basetypes.StringValue, was: %T`, rawDescriptionAttribute))
	}

	rawEndUserDescriptionAttribute, ok := attributes["raw_end_user_description"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`raw_end_user_description is missing from object`)

		return nil, diags
	}

	rawEndUserDescriptionVal, ok := rawEndUserDescriptionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`raw_end_user_description expected to be basetypes.StringValue, was: %T`, rawEndUserDescriptionAttribute))
	}

	rawEndUserLabelAttribute, ok := attributes["raw_end_user_label"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`raw_end_user_label is missing from object`)

		return nil, diags
	}

	rawEndUserLabelVal, ok := rawEndUserLabelAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`raw_end_user_label expected to be basetypes.StringValue, was: %T`, rawEndUserLabelAttribute))
	}

	statusCategoryAttribute, ok := attributes["status_category"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`status_category is missing from object`)

		return nil, diags
	}

	statusCategoryVal, ok := statusCategoryAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`status_category expected to be basetypes.StringValue, was: %T`, statusCategoryAttribute))
	}

	updatedAtAttribute, ok := attributes["updated_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`updated_at is missing from object`)

		return nil, diags
	}

	updatedAtVal, ok := updatedAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`updated_at expected to be basetypes.StringValue, was: %T`, updatedAtAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return CustomStatusValue{
		Active:                activeVal,
		AgentLabel:            agentLabelVal,
		CreatedAt:             createdAtVal,
		Default:               defaultVal,
		Description:           descriptionVal,
		EndUserDescription:    endUserDescriptionVal,
		EndUserLabel:          endUserLabelVal,
		Id:                    idVal,
		RawAgentLabel:         rawAgentLabelVal,
		RawDescription:        rawDescriptionVal,
		RawEndUserDescription: rawEndUserDescriptionVal,
		RawEndUserLabel:       rawEndUserLabelVal,
		StatusCategory:        statusCategoryVal,
		UpdatedAt:             updatedAtVal,
		state:                 attr.ValueStateKnown,
	}, diags
}

func NewCustomStatusValueNull() CustomStatusValue {
	return CustomStatusValue{
		state: attr.ValueStateNull,
	}
}

func NewCustomStatusValueUnknown() CustomStatusValue {
	return CustomStatusValue{
		state: attr.ValueStateUnknown,
	}
}

func NewCustomStatusValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (CustomStatusValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing CustomStatusValue Attribute Value",
				"While creating a CustomStatusValue value, a missing attribute value was detected. "+
					"A CustomStatusValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("CustomStatusValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid CustomStatusValue Attribute Type",
				"While creating a CustomStatusValue value, an invalid attribute value was detected. "+
					"A CustomStatusValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("CustomStatusValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("CustomStatusValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra CustomStatusValue Attribute Value",
				"While creating a CustomStatusValue value, an extra attribute value was detected. "+
					"A CustomStatusValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra CustomStatusValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewCustomStatusValueUnknown(), diags
	}

	activeAttribute, ok := attributes["active"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`active is missing from object`)

		return NewCustomStatusValueUnknown(), diags
	}

	activeVal, ok := activeAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`active expected to be basetypes.BoolValue, was: %T`, activeAttribute))
	}

	agentLabelAttribute, ok := attributes["agent_label"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`agent_label is missing from object`)

		return NewCustomStatusValueUnknown(), diags
	}

	agentLabelVal, ok := agentLabelAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`agent_label expected to be basetypes.StringValue, was: %T`, agentLabelAttribute))
	}

	createdAtAttribute, ok := attributes["created_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`created_at is missing from object`)

		return NewCustomStatusValueUnknown(), diags
	}

	createdAtVal, ok := createdAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`created_at expected to be basetypes.StringValue, was: %T`, createdAtAttribute))
	}

	defaultAttribute, ok := attributes["default"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`default is missing from object`)

		return NewCustomStatusValueUnknown(), diags
	}

	defaultVal, ok := defaultAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`default expected to be basetypes.BoolValue, was: %T`, defaultAttribute))
	}

	descriptionAttribute, ok := attributes["description"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`description is missing from object`)

		return NewCustomStatusValueUnknown(), diags
	}

	descriptionVal, ok := descriptionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`description expected to be basetypes.StringValue, was: %T`, descriptionAttribute))
	}

	endUserDescriptionAttribute, ok := attributes["end_user_description"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`end_user_description is missing from object`)

		return NewCustomStatusValueUnknown(), diags
	}

	endUserDescriptionVal, ok := endUserDescriptionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`end_user_description expected to be basetypes.StringValue, was: %T`, endUserDescriptionAttribute))
	}

	endUserLabelAttribute, ok := attributes["end_user_label"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`end_user_label is missing from object`)

		return NewCustomStatusValueUnknown(), diags
	}

	endUserLabelVal, ok := endUserLabelAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`end_user_label expected to be basetypes.StringValue, was: %T`, endUserLabelAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return NewCustomStatusValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.Int64Value, was: %T`, idAttribute))
	}

	rawAgentLabelAttribute, ok := attributes["raw_agent_label"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`raw_agent_label is missing from object`)

		return NewCustomStatusValueUnknown(), diags
	}

	rawAgentLabelVal, ok := rawAgentLabelAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`raw_agent_label expected to be basetypes.StringValue, was: %T`, rawAgentLabelAttribute))
	}

	rawDescriptionAttribute, ok := attributes["raw_description"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`raw_description is missing from object`)

		return NewCustomStatusValueUnknown(), diags
	}

	rawDescriptionVal, ok := rawDescriptionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`raw_description expected to be basetypes.StringValue, was: %T`, rawDescriptionAttribute))
	}

	rawEndUserDescriptionAttribute, ok := attributes["raw_end_user_description"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`raw_end_user_description is missing from object`)

		return NewCustomStatusValueUnknown(), diags
	}

	rawEndUserDescriptionVal, ok := rawEndUserDescriptionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`raw_end_user_description expected to be basetypes.StringValue, was: %T`, rawEndUserDescriptionAttribute))
	}

	rawEndUserLabelAttribute, ok := attributes["raw_end_user_label"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`raw_end_user_label is missing from object`)

		return NewCustomStatusValueUnknown(), diags
	}

	rawEndUserLabelVal, ok := rawEndUserLabelAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`raw_end_user_label expected to be basetypes.StringValue, was: %T`, rawEndUserLabelAttribute))
	}

	statusCategoryAttribute, ok := attributes["status_category"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`status_category is missing from object`)

		return NewCustomStatusValueUnknown(), diags
	}

	statusCategoryVal, ok := statusCategoryAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`status_category expected to be basetypes.StringValue, was: %T`, statusCategoryAttribute))
	}

	updatedAtAttribute, ok := attributes["updated_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`updated_at is missing from object`)

		return NewCustomStatusValueUnknown(), diags
	}

	updatedAtVal, ok := updatedAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`updated_at expected to be basetypes.StringValue, was: %T`, updatedAtAttribute))
	}

	if diags.HasError() {
		return NewCustomStatusValueUnknown(), diags
	}

	return CustomStatusValue{
		Active:                activeVal,
		AgentLabel:            agentLabelVal,
		CreatedAt:             createdAtVal,
		Default:               defaultVal,
		Description:           descriptionVal,
		EndUserDescription:    endUserDescriptionVal,
		EndUserLabel:          endUserLabelVal,
		Id:                    idVal,
		RawAgentLabel:         rawAgentLabelVal,
		RawDescription:        rawDescriptionVal,
		RawEndUserDescription: rawEndUserDescriptionVal,
		RawEndUserLabel:       rawEndUserLabelVal,
		StatusCategory:        statusCategoryVal,
		UpdatedAt:             updatedAtVal,
		state:                 attr.ValueStateKnown,
	}, diags
}

func NewCustomStatusValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) CustomStatusValue {
	object, diags := NewCustomStatusValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewCustomStatusValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t CustomStatusType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewCustomStatusValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewCustomStatusValueUnknown(), nil
	}

	if in.IsNull() {
		return NewCustomStatusValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewCustomStatusValueMust(CustomStatusValue{}.AttributeTypes(ctx), attributes), nil
}

func (t CustomStatusType) ValueType(ctx context.Context) attr.Value {
	return CustomStatusValue{}
}

var _ basetypes.ObjectValuable = CustomStatusValue{}

type CustomStatusValue struct {
	Active                basetypes.BoolValue   `tfsdk:"active"`
	AgentLabel            basetypes.StringValue `tfsdk:"agent_label"`
	CreatedAt             basetypes.StringValue `tfsdk:"created_at"`
	Default               basetypes.BoolValue   `tfsdk:"default"`
	Description           basetypes.StringValue `tfsdk:"description"`
	EndUserDescription    basetypes.StringValue `tfsdk:"end_user_description"`
	EndUserLabel          basetypes.StringValue `tfsdk:"end_user_label"`
	Id                    basetypes.Int64Value  `tfsdk:"id"`
	RawAgentLabel         basetypes.StringValue `tfsdk:"raw_agent_label"`
	RawDescription        basetypes.StringValue `tfsdk:"raw_description"`
	RawEndUserDescription basetypes.StringValue `tfsdk:"raw_end_user_description"`
	RawEndUserLabel       basetypes.StringValue `tfsdk:"raw_end_user_label"`
	StatusCategory        basetypes.StringValue `tfsdk:"status_category"`
	UpdatedAt             basetypes.StringValue `tfsdk:"updated_at"`
	state                 attr.ValueState
}

func (v CustomStatusValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 14)

	var val tftypes.Value
	var err error

	attrTypes["active"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["agent_label"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["created_at"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["default"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["description"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["end_user_description"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["end_user_label"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["id"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["raw_agent_label"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["raw_description"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["raw_end_user_description"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["raw_end_user_label"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["status_category"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["updated_at"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 14)

		val, err = v.Active.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["active"] = val

		val, err = v.AgentLabel.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["agent_label"] = val

		val, err = v.CreatedAt.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["created_at"] = val

		val, err = v.Default.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["default"] = val

		val, err = v.Description.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["description"] = val

		val, err = v.EndUserDescription.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["end_user_description"] = val

		val, err = v.EndUserLabel.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["end_user_label"] = val

		val, err = v.Id.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["id"] = val

		val, err = v.RawAgentLabel.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["raw_agent_label"] = val

		val, err = v.RawDescription.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["raw_description"] = val

		val, err = v.RawEndUserDescription.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["raw_end_user_description"] = val

		val, err = v.RawEndUserLabel.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["raw_end_user_label"] = val

		val, err = v.StatusCategory.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["status_category"] = val

		val, err = v.UpdatedAt.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["updated_at"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v CustomStatusValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v CustomStatusValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v CustomStatusValue) String() string {
	return "CustomStatusValue"
}

func (v CustomStatusValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	objVal, diags := types.ObjectValue(
		map[string]attr.Type{
			"active":                   basetypes.BoolType{},
			"agent_label":              basetypes.StringType{},
			"created_at":               basetypes.StringType{},
			"default":                  basetypes.BoolType{},
			"description":              basetypes.StringType{},
			"end_user_description":     basetypes.StringType{},
			"end_user_label":           basetypes.StringType{},
			"id":                       basetypes.Int64Type{},
			"raw_agent_label":          basetypes.StringType{},
			"raw_description":          basetypes.StringType{},
			"raw_end_user_description": basetypes.StringType{},
			"raw_end_user_label":       basetypes.StringType{},
			"status_category":          basetypes.StringType{},
			"updated_at":               basetypes.StringType{},
		},
		map[string]attr.Value{
			"active":                   v.Active,
			"agent_label":              v.AgentLabel,
			"created_at":               v.CreatedAt,
			"default":                  v.Default,
			"description":              v.Description,
			"end_user_description":     v.EndUserDescription,
			"end_user_label":           v.EndUserLabel,
			"id":                       v.Id,
			"raw_agent_label":          v.RawAgentLabel,
			"raw_description":          v.RawDescription,
			"raw_end_user_description": v.RawEndUserDescription,
			"raw_end_user_label":       v.RawEndUserLabel,
			"status_category":          v.StatusCategory,
			"updated_at":               v.UpdatedAt,
		})

	return objVal, diags
}

func (v CustomStatusValue) Equal(o attr.Value) bool {
	other, ok := o.(CustomStatusValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Active.Equal(other.Active) {
		return false
	}

	if !v.AgentLabel.Equal(other.AgentLabel) {
		return false
	}

	if !v.CreatedAt.Equal(other.CreatedAt) {
		return false
	}

	if !v.Default.Equal(other.Default) {
		return false
	}

	if !v.Description.Equal(other.Description) {
		return false
	}

	if !v.EndUserDescription.Equal(other.EndUserDescription) {
		return false
	}

	if !v.EndUserLabel.Equal(other.EndUserLabel) {
		return false
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	if !v.RawAgentLabel.Equal(other.RawAgentLabel) {
		return false
	}

	if !v.RawDescription.Equal(other.RawDescription) {
		return false
	}

	if !v.RawEndUserDescription.Equal(other.RawEndUserDescription) {
		return false
	}

	if !v.RawEndUserLabel.Equal(other.RawEndUserLabel) {
		return false
	}

	if !v.StatusCategory.Equal(other.StatusCategory) {
		return false
	}

	if !v.UpdatedAt.Equal(other.UpdatedAt) {
		return false
	}

	return true
}

func (v CustomStatusValue) Type(ctx context.Context) attr.Type {
	return CustomStatusType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v CustomStatusValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"active":                   basetypes.BoolType{},
		"agent_label":              basetypes.StringType{},
		"created_at":               basetypes.StringType{},
		"default":                  basetypes.BoolType{},
		"description":              basetypes.StringType{},
		"end_user_description":     basetypes.StringType{},
		"end_user_label":           basetypes.StringType{},
		"id":                       basetypes.Int64Type{},
		"raw_agent_label":          basetypes.StringType{},
		"raw_description":          basetypes.StringType{},
		"raw_end_user_description": basetypes.StringType{},
		"raw_end_user_label":       basetypes.StringType{},
		"status_category":          basetypes.StringType{},
		"updated_at":               basetypes.StringType{},
	}
}
