// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package provider_andsafe_zendesk_provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/provider/schema"
)

func AndsafeZendeskProviderProviderSchema(ctx context.Context) schema.Schema {
	return schema.Schema{}
}

type AndsafeZendeskProviderModel struct {
}
